### PR TITLE
Added routing and jsp pages

### PR DESCRIPTION
**Pull request by AndyGee**
Still very much in progress, but puts a few more things in place for the overall structure

### CODE REVIEW

**Comment by karianna** [comment]
I'm probably missing something here but do we actually need to have JSPs?  Since we're using Typescript and AngularJS can the UI not be a pure HTML app?

**Comment by kenfinnigan** [comment]
I'm also confused by the need for JSPs

**Comment by AndyGee** [comment]
Sure, there is currently no 'need' for jsps, but I really wanted to showcase the integration and mix in a bit of EE on the UI app. There is an element of a blog post coming in there later. It's just to show that it can be done, and was one of my first questions (coming from a very strong EE background) - Currently there is very little out there in google land that puts this all together, but many asking for it.
I only see an 'added' value there (jsps take nothing away from naked html, only add), and I feel that Microprofile is also here to serve the wider EE community that will be looking at this. So I guess I am looking for a meetup of the purists and the EE guys. How does that make you feel? (Warm I hope).

**Comment by AndyGee** [comment]
That said, if you want to use an html template for your corresponding components I guess that's pretty easy to do - I'm just filling out the ui app as I'm learning Angular2.

**Comment by karianna** [comment]
Hi @AndyGee - So I feel strongly about removing all other EE aspects apart from the core 3 that MP is supporting.  Perception means a lot and if people looking at the sample app see EJBs (which I know where's removing) and JSPs they'll get the impression that MP is just Java EE.

**Comment by AndyGee** [comment]
OK, I'll make the endpoint urls lookup a rest callback - merge this and I'll sort it out on the next pr- as said, it's in progress - the next 4 days I'll be on this.

**Pull request merged**
