### PR TITLE
Add liberty build

### PR DESCRIPTION
**Pull request by iainduncani**

### CODE REVIEW

**Comment by kenfinnigan** [comment]
I didn't think we wanted every service to be runnable on every implementation.

I thought the point of this was showcasing multiple implementations working together?

**Comment by karianna** [comment]
I think it's fine to show each service being capable of being run in any vendor's impl.  As long as the quickstart has a 'per vendor' approach.  That said this might be worth discussing in the mailing list. As a side note I've submitted another bug on the quick start as it is sadly broken.

**Comment by iainduncani** [comment]
@kenfinnigan yes, you are right, this was a personal test to make sure that all the services ran on Liberty to make sure the server was capable of doing so and was not meant to be pulled into here. I had meant to create the PR against a different repo but it went to this one by accident. I will revert this though I guess as it's now in master it is best to do this with a new commit + PR rather than re-writting history.

**Comment by iainduncani** [comment]
@kenfinnigan yes, you are right, this was a personal test to make sure that all the services ran on Liberty to make sure the server was capable of doing so and was not meant to be pulled into here. I had meant to create the PR against a different repo but it went to this one by accident. I will revert this though I guess as it's now in master it is best to do this with a new commit + PR rather than re-writting history.

**Comment by iainduncani** [comment]
@kenfinnigan yes, you are right, this was a personal test to make sure that all the services ran on Liberty to make sure the server was capable of doing so and was not meant to be pulled into here. I had meant to create the PR against a different repo but it went to this one by accident. I will revert this though I guess as it's now in master it is best to do this with a new commit + PR rather than re-writting history.

**Comment by iainduncani** [comment]
@kenfinnigan yes, you are right, this was a personal test to make sure that all the services ran on Liberty to make sure the server was capable of doing so and was not meant to be pulled into here. I had meant to create the PR against a different repo but it went to this one by accident. I will revert this though I guess as it's now in master it is best to do this with a new commit + PR rather than re-writting history.

**Comment by iainduncani** [comment]
@kenfinnigan yes, you are right, this was a personal test to make sure that all the services ran on Liberty to make sure the server was capable of doing so and was not meant to be pulled into here. I had meant to create the PR against a different repo but it went to this one by accident. I will revert this though I guess as it's now in master it is best to do this with a new commit + PR rather than re-writting history.

**Comment by iainduncani** [comment]
@kenfinnigan yes, you are right, this was a personal test to make sure that all the services ran on Liberty to make sure the server was capable of doing so and was not meant to be pulled into here. I had meant to create the PR against a different repo but it went to this one by accident. I will revert this though I guess as it's now in master it is best to do this with a new commit + PR rather than re-writting history.

**Comment by iainduncani** [comment]
@kenfinnigan yes, you are right, this was a personal test to make sure that all the services ran on Liberty to make sure the server was capable of doing so and was not meant to be pulled into here. I had meant to create the PR against a different repo but it went to this one by accident. I will revert this though I guess as it's now in master it is best to do this with a new commit + PR rather than re-writting history.

**Comment by iainduncani** [comment]
@kenfinnigan yes, you are right, this was a personal test to make sure that all the services ran on Liberty to make sure the server was capable of doing so and was not meant to be pulled into here. I had meant to create the PR against a different repo but it went to this one by accident. I will revert this though I guess as it's now in master it is best to do this with a new commit + PR rather than re-writting history.

**Comment by iainduncani** [comment]
@kenfinnigan yes, you are right, this was a personal test to make sure that all the services ran on Liberty to make sure the server was capable of doing so and was not meant to be pulled into here. I had meant to create the PR against a different repo but it went to this one by accident. I will revert this though I guess as it's now in master it is best to do this with a new commit + PR rather than re-writting history.

**Comment by iainduncani** [comment]
@kenfinnigan yes, you are right, this was a personal test to make sure that all the services ran on Liberty to make sure the server was capable of doing so and was not meant to be pulled into here. I had meant to create the PR against a different repo but it went to this one by accident. I will revert this though I guess as it's now in master it is best to do this with a new commit + PR rather than re-writting history.

**Comment by iainduncani** [comment]
@kenfinnigan yes, you are right, this was a personal test to make sure that all the services ran on Liberty to make sure the server was capable of doing so and was not meant to be pulled into here. I had meant to create the PR against a different repo but it went to this one by accident. I will revert this though I guess as it's now in master it is best to do this with a new commit + PR rather than re-writting history.

**Comment by iainduncani** [comment]
@kenfinnigan yes, you are right, this was a personal test to make sure that all the services ran on Liberty to make sure the server was capable of doing so and was not meant to be pulled into here. I had meant to create the PR against a different repo but it went to this one by accident. I will revert this though I guess as it's now in master it is best to do this with a new commit + PR rather than re-writting history.

**Comment by iainduncani** [comment]
@kenfinnigan yes, you are right, this was a personal test to make sure that all the services ran on Liberty to make sure the server was capable of doing so and was not meant to be pulled into here. I had meant to create the PR against a different repo but it went to this one by accident. I will revert this though I guess as it's now in master it is best to do this with a new commit + PR rather than re-writting history.

**Comment by iainduncani** [comment]
@kenfinnigan yes, you are right, this was a personal test to make sure that all the services ran on Liberty to make sure the server was capable of doing so and was not meant to be pulled into here. I had meant to create the PR against a different repo but it went to this one by accident. I will revert this though I guess as it's now in master it is best to do this with a new commit + PR rather than re-writting history.

**Comment by iainduncani** [comment]
@kenfinnigan yes, you are right, this was a personal test to make sure that all the services ran on Liberty to make sure the server was capable of doing so and was not meant to be pulled into here. I had meant to create the PR against a different repo but it went to this one by accident. I will revert this though I guess as it's now in master it is best to do this with a new commit + PR rather than re-writting history.

**Comment by karianna** [comment]
Cool - consider my opinion on this overridden!

**Comment by iainduncani** [comment]
@karianna ha, I posted that before seeing your response, have taken your advice and switched to a discussion on the mailing list:
https://groups.google.com/forum/#!topic/microprofile/3lSd2ZeAKCc
Will hold off doing the revert commit for now until that has reach a conclusion.

**Pull request merged**
