### PR TITLE
Bootstrap schedule service from initial dataset

### PR DESCRIPTION
**Pull request by heiko-braun**
- The schedule service now aligns with the initial data that both session and speaker services hold when the demo starts
- Simplify the internal data model  to match the bootstrap data.
- Adopt test to new data structures

### CODE REVIEW

**Comment by heiko-braun** [comment]
Please hold until @ivannov has reviewed the changes

**Comment by heiko-braun** [comment]
@ivannov I've took the opportunity to align the initial schedule data with speaker and session services. Please take a look if this works for and decide if you want to accept it. It's merely an attempt to prepare the demo for j1.

**Comment by heiko-braun** [comment]
@ivannov I've deliberately removed the session entity model, because I think it belongs to the session service. Therefore I've added foreign key references. But with changes in place these should be consistent with the data the session service holds and thus could be looked up there.

**Comment by heiko-braun** [comment]
Merge before https://github.com/microprofile/microprofile-conference/pull/42

**Comment by heiko-braun** [comment]
rebased with current master

**Comment by heiko-braun** [comment]
@karianna & @AndyGee Should we proceed and merge if @ivannov doesn't respond in a timely manner? I would be good to cleanup the demo before Monday.

**Comment by AndyGee** [comment]
Yes, that's fair

**Comment by ivannov** [comment]
OK, I see that everything's done, but let me explain why I did it like it was before (and why I still think it should be done as I did it).

I am totally with you that the current conference microservices are not really such in the terms of DDD's bounded context sense. But we are using this app as a showcase, that is why we wanted to make some compromises with the business model in order to have a working and rather simple MP example.

That is why I defined the schedule service bounded context. A schedule has a session and the session has a speaker. But the schedule has its own database and doesn't know anything about session's and speaker's PKs in the other microservices - it lives in a world of its own. So it has its own representation of Session and Speaker. Which have just the attributes a session needs. This is what I understood from Eric Evans's Domain Driven Design book and this is how I think microservices should be implemented.

Now the schedule service is not a real microservice, but that is just my opinion. You are the owners of this showcase app, so I am just going to conform to the setup that you created and add the final method (@PUT update schedule). Then it's all yours ;)

**Comment by heiko-braun** [comment]
@ivannov I am not very experienced with domain driven design, but what you describe makes sense to me. I would suggest we simply regard this a learning exercise, prepare then first version for next week based on what we have and then continue the discussion and revisit the conference app after Java One. Would this work for you?

**Comment by kenfinnigan** [comment]
I can fully appreciate that what we have so far doesn't conform to DDD principles, but we did discuss this on the forum and mostly agree that for JavaOne it was likely necessary.

Sure the Schedule service could retain its own copy of data for Session and Speaker, but that would open the door to a whole raft of issues in terms of out of sync data if Speaker is updated but Schedule isn't informed, etc.

For JavaOne we're not expecting this to be the perfect showcase of how to develop microservices. It's merely the current iteration based on what MicroProfile makes available. Going forward as we look to focus more on DDD and other microservice related concerns, we will need to resolve this kind of problem and maybe even restructure how the services are grouped.

**Comment by ivannov** [comment]
I fully agree with you. Schedule should have never been a microservice of its own anyway, but we needed 4 of them for each vendor. So you are right, let's focus on making something runnable for J1 and let's hope that after that we'll revise the current setup :)

**Pull request merged**
