### PR TITLE
String IDs for bootstrap model and APIs

### PR DESCRIPTION
**Pull request by AndyGee**
The ability to seed the model with non specific data type IDs allows for future flexibility, especially when using UUIDs. This does not invalidate the bootstrap data, which still uses i++ for generated model.

I know this might be a point of contention, so here's my reasoning.

New UUIDs can be generated offline without parsing existing IDs.
Unique across/between applications.
No client side ambiguity.
Data replication/migration is substantially easier.
ORM's like them.
No PK/FK ambiguity.

### CODE REVIEW

**Comment by karianna** [comment]
Isn't this premature optimisation?

**Comment by AndyGee** [comment]
I'm kind of wanting to use it right now in UI and just wanted to stabilize it now rather than later.

**Comment by karianna** [comment]
Users of the app are entering their own IDs?

**Comment by AndyGee** [comment]
No not at all, I would never start any kind of persistence project on int/long these days.
I can see the next big conference coming, and this just ensures we can import anything.

**Comment by karianna** [comment]
I've always personally been against String IDs due to performance and indexing reasons.  But I think it's only fair that this doesn't get held up because of my opinion since I'm not actually contributing code to this app :-).  Perhaps see what others say first though?

**Comment by AndyGee** [comment]
Sure, and I don't think there is any major db out there any more that doesn't support the UUID datatype - which is two longs, so very fast to index.

**Comment by AndyGee** [comment]
Is anyone totally against this idea?

**Pull request merged**
