### PR TITLE
Fix the voting service URL and supply some preliminary data to the demo

### PR DESCRIPTION
**Pull request by heiko-braun**

### CODE REVIEW

**Comment by heiko-braun** [comment]
@Emily-Jiang yes, sorry, we'd been in a rush this morning to prop the demo. Here's the proper fix to that passes the tests: #116 116

**Comment by Emily-Jiang** [comment]
@heiko-braun Your #116 broke another test.  Kate and I just fixed all the tests. May I suggest in the future you run all the tests before you send PR:o?

**Comment by heiko-braun** [comment]
For #116 all tests did pass for me. Which problem did you see?

**Comment by heiko-braun** [comment]
Ah, I see. The voting service has additional integration tests. I didn't consider these. Apologies for the trouble.

**Pull request merged**
