### PR TITLE
Jcache example

### PR DESCRIPTION
**Pull request by OndrejM**
This is an example of using JCache to provide caching. 
Payara Micro includes hazelcast that provides distributed cache across all connected cluster members. It also provides means to pass messages using cache listeners (example is not provided yet). 

So far, the implementation relies on jcache-api provided by the runtime. CacheManager is created by a CDI producer when first needed, a cache is used to store data accessed by ScheduleDAO instead of a hashmap. Can easily be extended to cache persistence layer when persistence is added. Application behaves as behore, but the data can be replicated to more nodes if you run multiple nodes. Tested with Payara Micro.

To see how it works, run `microservice-schedule.jar` multiple times on the same machine:

```
java -jar target/microservice-schedule.jar [Options]
java -jar target/microservice-schedule.jar [Options]
java -jar target/microservice-schedule.jar [Options]
```

When multiple instances are running, use `ScheduleResource` REST endpoint to store some data using one of the nodes (e.g. at port 8080). Then restart the node. After restart, the very same data should be available, as they are retrieved from the other nodes in the cluster.

### CODE REVIEW

**Comment by OndrejM** [comment]
I created a PR to master branch as I cannot create new branches. This is an experimental proposal and works only with runtimes that provide JCache (like Payara, perhaps TomEE).
Therefore I would rather put it into a separate branch.

**Comment by karianna** [comment]
@OndrejM LMK if you have any troubles getting this into the samples project.

**Comment by mikecroft** [comment]
Is there anywhere where this process is documented? e.g. a "how to contribute" page off microprofile.io? For someone new to the project who wanted to submit a proposal via example like this, there's very little guidance on what goes where and it seems like the only way to find out is to comb the last few months of posts in the Google group. Even the microprofile-samples project isn't really named in a way that makes it obvious that proposals could be accepted there. (would it make sense to have a `microprofile-proposals` project which is pretty open and lets anyone add a module? The process could be something like....open GitHub issue for the proposal then open a PR with a module named after the GH issue id to keep them in sync)

I'm very happy to help out and create a page to describe all the stuff that's currently agreed!

/cc @gregrluck

**Comment by karianna** [comment]
Hi @mikecroft - I think that's a good idea.  Perhaps the base microprofile org could have a README explaining all of the various repos as well.  I'd take this to the mailing list for general discussion.

**Pull request closed without merging**
