### PR TITLE
Add liberty build information

### PR DESCRIPTION
**Pull request by iainduncani**

### CODE REVIEW

**Comment by kenfinnigan** [comment]
My understanding was that each service would be run with a specific runtime:

Speaker - TomEE
Session - WF Swarm
Schedule - Payara
Vote - Liberty

Right now I don't think we need profiles for each runtime for every service

**Comment by heiko-braun** [comment]
I agree with @kenfinnigan and did assume that each service uses it's own toolkit/runtime. I would suggest to describe in the `readme.doc` how each service is started according to it's own toolkit, like we did for Swarm.

**Comment by iduncani** [comment]
Sure thing, I wasn't quite sure if we wanted this in the main repo or not but I wanted to make sure each part could at least run on Liberty as a way of testing it.  I'll close this as there should be another PR coming from Tom or Emily soon with the vote service in.

@kenfinnigan if the Schedule is for Payara should we remove the swarm profile that @agoncal added to it's pom.xml in this commit https://github.com/microprofile/microprofile-conference/commit/29dbd51a423f2a3f14d75fc61b5753a7a4a396bf

**Comment by kenfinnigan** [comment]
@iainduncani yes we should remove swarm profile from Schedule

**Pull request closed without merging**
